### ISSUE TITLE
Admin page 

### ISSUE THREAD

**Issue by carlyjames** [Underemployed/PHP-MySQL-Blog-Website-with-Admin-Panel#1]
the admin page takes time to load and still displays nothing

**Comment by Underemployed** [comment]
All good here! As you can see in the screenshots:

  -  Try a different browser.
  -  Update your browser for optimal performance.
- Review extensions - they might disrupt search.
 -   Clear cache & cookies for a fresh start.
- The issue could be due to high latency (delay) in the connection.
Note: My experience is on Windows.
<div style="display: flex; flex-direction: row; gap: 20px;">
    <img src="https://github.com/Underemployed/PHP-MySQL-Blog-Website-with-Admin-Panel/assets/116073306/843c21cb-1d1a-48fa-a3e4-d23f34c07181" alt="Admin Page" height="200px">
    <img src="https://github.com/Underemployed/PHP-MySQL-Blog-Website-with-Admin-Panel/assets/116073306/6a1298ae-844a-4593-86b9-b27e9085d1f8" alt="Admin Page" height="200px">
</div>
